### ISSUE TITLE
Is there a way to use SCSS in payload custom components while using tailwind in the frontend?

### ISSUE THREAD

**Issue by linobino1** [manawiki/repay#18]
Using `@import '~payload/scss'` in a `.scss` file that is being imported (maybe indirectly) in `payload.config.ts` raises an error:

```
Error: Can't find stylesheet to import.
    ╷
  1 │ @import "~payload/scss";
    │   
```

**Comment by linobino1** [comment]
A simple solution: Do not use `@import "~payload/scss"` 😆 it will still work

**Comment by linobino1** [comment]
Better solution: use `@import 'payload/scss';`, that gives you access to the payload variables/functions.

**Comment by xHomu** [comment]
The `~` tsconfig path alias tends to create compatibility issues like this, that's why a lot of Remix templates are moving toward using package.json alias instead:

https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/026-path-aliases.md

I'll probably switch over once Typescript's adoption of this standard stabilize here https://github.com/microsoft/TypeScript/pull/55015

**Comment by linobino1** [comment]
I see, thank you for the explanation!On 11 Feb 2024, at 21:13, xHomu ***@***.***> wrote:﻿
The ~ tsconfig path alias tends to create compatibility issues like this, that's why a lot of Remix templates are moving toward using package.json alias instead:
https://github.com/epicweb-dev/epic-stack/blob/main/docs/decisions/026-path-aliases.md
I'll probably switch over once Typescript's adoption of this standard stabilize here microsoft/TypeScript#55015
